baseURL = 'https://cloakforge.cc/'
languageCode = 'en-US'
title = 'Cloakforge'

[menus]
  [[menus.main]]
    name = 'Apps'
    pageRef = '/'
    weight = 10



[module]
  [module.hugoVersion]
    extended = false
    min = '0.146.0'
